### ISSUE TITLE
Uncaught SyntaxError: Unexpected token P

### ISSUE THREAD

**Issue by pyfisch** [jakesankey/git-history#3]
[Enter steps to reproduce below:]
1. Get history for a file

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package, v1.1.2
### Stack Trace

Uncaught SyntaxError: Unexpected token P

```
At file:///usr/share/atom/resources/app/static/index.html?loadSettings=%7B%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.165.0%22%2C%22shellLoadTime%22%3A1197%7D:1

SyntaxError: Unexpected token P
  at Object.parse (native)
  at stdout (/home/michael/.atom/packages/git-history/lib/git-history-view.coffee:26:13)
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:162:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:514:20)

```
### Commands

```
 21x -0:49.9 core:move-up (input.hidden-input)
undefined -0:41.1 core:move-down (input.hidden-input)
  5x -0:25.7 core:move-right (input.hidden-input)
 14x -0:24.2 core:move-left (input.hidden-input)
 49x -0:23.0 core:move-up (input.hidden-input)
     -0:20.8 core:move-down (input.hidden-input)
 50x -0:20.5 core:move-left (input.hidden-input)
  4x -0:17.4 core:move-right (input.hidden-input)
undefined -0:15.6 core:move-down (input.hidden-input)
     -0:00.0 git-history:show-file-history (input.hidden-input)
```
### Config

```
{}
```
### Installed Packages

``` coffee
# User
editorconfig, v0.2.2
geojson-preview, v0.3.3
git-history, v1.1.2
language-dot, v1.5.0
language-rust, v0.3.2
linter-rust, v0.0.3
tag, v0.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by carlisia** [comment]
Getting the same, except mine says 'token M'. It happens with both crtl-alt-o and crtl-alt-h.

**Comment by jakesankey** [comment]
Is there any additional info you can provide? On the latest version of the plugin and Atom, I am unable to reproduce this scenario.

**Comment by pyfisch** [comment]
For me it works now v1.1.3 of the plugin is installed. Before it was v1.1.2.

**Comment by jakesankey** [comment]
Great!
