### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 

### ISSUE THREAD

**Issue by alexbuijs** [jakesankey/git-history#37]
When doing git show file history on a file, I get this error.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package, v3.2.0
### Stack Trace

Uncaught SyntaxError: Unexpected token 

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FUsers%2Fbuijs%2FProjects%2FYoungCapital%2Fcapitalizr%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fbuijs%2FProjects%2FYoungCapital%2Fcapitalizr%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%2C%22forceAddToWindow%22%3Afalse%7D%5D%2C%22windowInitializationScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22windowDimensions%22%3A%7B%22x%22%3A44%2C%22y%22%3A67%2C%22width%22%3A2165%2C%22height%22%3A1252%7D%2C%22profileStartup%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22env%22%3A%7B%22JAVA_HOME%22%3A%22%2FLibrary%2FJava%2FJavaVirtualMachines%2Fjdk1.8.0_31.jdk%2FContents%2FHome%22%2C%22ITERM_SESSION_ID%22%3A%22w0t2p1%3A33D59D51-26CE-48D7-B5B8-3F7D79843015%22%2C%22TMPDIR%22%3A%22%2Fvar%2Ffolders%2F86%2F85zdfvp16fxc809gfxy4nlhc0000gn%2FT%2F%22%2C%22TERM_PROGRAM%22%3A%22iTerm.app%22%2C%22COLORFGBG%22%3A%227%3B0%22%2C%22__CF_USER_TEXT_ENCODING%22%3A%220x1F5%3A0x0%3A0x0%22%2C%22SHELL%22%3A%22%2Fbin%2Fbash%22%2C%22HOME%22%3A%22%2FUsers%2Fbuijs%22%2C%22RUBYOPT%22%3A%22%22%2C%22_%22%3A%22%2Fusr%2Fbin%2Fopen%22%2C%22DOCKER_CERT_PATH%22%3A%22%2FUsers%2Fbuijs%2F.docker%2Fmachine%2Fmachines%2Fdev%22%2C%22RUBY_VERSION%22%3A%222.3.0%22%2C%22SSH_AUTH_SOCK%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.D0SI6KJJxo%2FListeners%22%2C%22CLICOLOR%22%3A%221%22%2C%22GEM_HOME%22%3A%22%2FUsers%2Fbuijs%2F.gem%2Fruby%2F2.3.0%22%2C%22TERM_PROGRAM_VERSION%22%3A%223.0.4%22%2C%22RUBY_ENGINE%22%3A%22ruby%22%2C%22SHLVL%22%3A%222%22%2C%22TERM_SESSION_ID%22%3A%22w0t2p1%3A33D59D51-26CE-48D7-B5B8-3F7D79843015%22%2C%22Apple_PubSub_Socket_Render%22%3A%22%2Fprivate%2Ftmp%2Fcom.apple.launchd.XtqPdBezDh%2FRender%22%2C%22GEM_ROOT%22%3A%22%2FUsers%2Fbuijs%2F.rubies%2Fruby-2.3.0%2Flib%2Fruby%2Fgems%2F2.3.0%22%2C%22EDITOR%22%3A%22atom%20-w%22%2C%22PATH%22%3A%22%2FUsers%2Fbuijs%2F.gem%2Fruby%2F2.3.0%2Fbin%3A%2FUsers%2Fbuijs%2F.rubies%2Fruby-2.3.0%2Flib%2Fruby%2Fgems%2F2.3.0%2Fbin%3A%2FUsers%2Fbuijs%2F.rubies%2Fruby-2.3.0%2Fbin%3A%2FUsers%2Fbuijs%2FProjects%2FYoungCapital%2Fandroid-sdk%2Fplatform-tools%3A%2FUsers%2Fbuijs%2FProjects%2FYoungCapital%2Fandroid-sdk%2Ftools%3A%2FUsers%2Fbuijs%2F.node%2Fbin%3A%2FSystem%2FLibrary%2FFrameworks%2FJavaVM.framework%2FVersions%3A%2FApplications%2FPostgres.app%2FContents%2FMacOS%2Fbin%3A%2Fusr%2Flocal%2Fshare%2Fnpm%2Fbin%3A%2Fusr%2Flocal%2Fheroku%2Fbin%3A%2Fusr%2Flocal%2Fsbin%3A%2Fopt%2Flocal%2Fshare%2Fman%3A%2Fopt%2Flocal%2Fsbin%3A%2Fopt%2Flocal%2Fbin%3A%2Fusr%2Flocal%2Fbin%3A%2Fusr%2Fbin%3A%2Fbin%3A%2Fusr%2Fsbin%3A%2Fsbin%22%2C%22TERM%22%3A%22xterm-256color%22%2C%22DOCKER_HOST%22%3A%22tcp%3A%2F%2F192.168.99.100%3A2376%22%2C%22DOCKER_TLS_VERIFY%22%3A%221%22%2C%22LOGNAME%22%3A%22buijs%22%2C%22RUBY_ROOT%22%3A%22%2FUsers%2Fbuijs%2F.rubies%2Fruby-2.3.0%22%2C%22LC_CTYPE%22%3A%22UTF-8%22%2C%22XPC_SERVICE_NAME%22%3A%22com.github.atom.52512.96F286D4-0A2C-4924-A5DE-7F9787F8AF58%22%2C%22GEM_PATH%22%3A%22%2FUsers%2Fbuijs%2F.gem%2Fruby%2F2.3.0%3A%2FUsers%2Fbuijs%2F.rubies%2Fruby-2.3.0%2Flib%2Fruby%2Fgems%2F2.3.0%22%2C%22DOCKER_MACHINE_NAME%22%3A%22dev%22%2C%22ITERM_PROFILE%22%3A%22Default%22%2C%22USER%22%3A%22buijs%22%2C%22XPC_FLAGS%22%3A%220x0%22%2C%22PWD%22%3A%22%2FUsers%2Fbuijs%2FProjects%2FYoungCapital%2Fcapitalizr%22%2C%22GOOGLE_API_KEY%22%3A%22AIzaSyAQfxPJiounkhOjODEO5ZieffeBv6yft2Q%22%2C%22ATOM_HOME%22%3A%22%2FUsers%2Fbuijs%2F.atom%22%7D%2C%22appVersion%22%3A%221.8.0%22%2C%22atomHome%22%3A%22%2FUsers%2Fbuijs%2F.atom%22%7D:1

SyntaxError: Unexpected token 
    at Object.parse (native)
    at stdout (/Users/buijs/.atom/packages/git-history/lib/git-history-view.coffee:46:13)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:87:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -0:03.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 git-history:show-file-history (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "linter-markdown"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "git-history": {
    "showDiff": false
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-alignment, v0.12.1
auto-indent, v0.5.0
autoclose-html, v0.23.0
coffeescript-check, v0.2.0
color-picker, v2.1.1
git-history, v3.2.0
highlight-selected, v0.11.2
language-haml, v0.24.0
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-haml, v1.2.0
linter-js-yaml, v1.2.5
linter-jsonlint, v1.2.4
linter-rubocop, v0.4.7
linter-scss-lint, v2.5.1
pigments, v0.26.0
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by schultzern** [comment]
1+
