### ISSUE TITLE
Uncaught ReferenceError: file is not defined

### ISSUE THREAD

**Issue by alexandre-g** [jakesankey/git-history#39]
[Enter steps to reproduce below:]

1. ... Install package
2. ... Press ctrl + alt + h

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package, v3.2.0

### Stack Trace

Uncaught ReferenceError: file is not defined

```
At C:\Users\alex\.atom\packages\git-history\lib\git-history-view.coffee:10

ReferenceError: file is not defined
    at GitHistoryView.initialize (file:///C:/Users/alex/.atom/packages/git-history/lib/git-history-view.coffee:10:20)
    at GitHistoryView.View [as constructor] (C:\Users\alex\.atom\packages\git-history\node_modules\space-pen\lib\space-pen.js:184:25)
    at GitHistoryView.SelectListView [as constructor] (C:\Users\alex\.atom\packages\git-history\node_modules\atom-space-pen-views\lib\select-list-view.js:18:51)
    at new GitHistoryView (file:///C:/Users/alex/.atom/packages/git-history/lib/git-history-view.coffee:6:7)
    at atom-text-editor.GitHistory._loadGitHistoryView (file:///C:/Users/alex/.atom/packages/git-history/lib/git-history.coffee:18:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\alex\AppData\Local\atom\app-1.12.5\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -1:57.3.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:45.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
 14x -1:42.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:39 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.3.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -1:02.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 git-history:show-file-history (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
git-history, v3.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by anestik** [comment]
Same issue here

**Atom Version**: 1.12.3
**System**: Ubuntu 14.04 LTS
**Thrown From**: git-history package, v3.2.0

**Comment by fcagalj** [comment]
+1

**Comment by jakesankey** [comment]
Sorry, I don't have much free time to investigate this right now. PRs are always welcome!

**Comment by nardeas** [comment]
For me, fixing a typo in initialize fixed this. I have PR waiting #40

**Comment by razzul** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package, v3.2.0


### Stack Trace

Uncaught ReferenceError: file is not defined

```
At C:\Users\Administrator\.atom\packages\git-history\lib\git-history-view.coffee:10

ReferenceError: file is not defined
    at GitHistoryView.initialize (file:///C:/Users/Administrator/.atom/packages/git-history/lib/git-history-view.coffee:10:20)
    at GitHistoryView.View [as constructor] (C:\Users\Administrator\.atom\packages\git-history\node_modules\space-pen\lib\space-pen.js:184:25)
    at GitHistoryView.SelectListView [as constructor] (C:\Users\Administrator\.atom\packages\git-history\node_modules\atom-space-pen-views\lib\select-list-view.js:18:51)
    at new GitHistoryView (file:///C:/Users/Administrator/.atom/packages/git-history/lib/git-history-view.coffee:6:7)
    at atom-text-editor.GitHistory._loadGitHistoryView (file:///C:/Users/Administrator/.atom/packages/git-history/lib/git-history.coffee:18:13)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:259:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.13.1\resources\app.asar\src\window-event-handler.js:3:59)
```

### Commands

```
     -1:43.1.0 settings-view:open (input.hidden-input)
     -1:33.3.0 core:paste (input.hidden-input)
     -0:33.8.0 tree-view:reveal-active-file (div.line)
  3x -0:30.1.0 core:close (input.hidden-input)
     -0:12.2.0 command-palette:toggle (input.hidden-input)
     -0:04.3.0 core:confirm (input.hidden-input)
     -0:04.3.0 git-history:show-file-history (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v1.0.2 (active)
atom-material-ui, v1.3.9 (active)
git-history, v3.2.0 (inactive)
git-plus, v7.2.0 (active)
linter, v1.11.21 (active)
linter-php, v1.3.1 (active)
minimap, v4.26.8 (active)
minimap-git-diff, v4.3.1 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
metrics, v1.1.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by PixelT** [comment]
+1

**Comment by Sly777** [comment]
+1

**Comment by maarteti** [comment]
+1

**Comment by bretproft** [comment]
+1

**Comment by FuzzyLitchi** [comment]
+1

**Comment by coderkk** [comment]
Fixed by change the line of code from "@show() if file" to "@show() if @file"

**Comment by wizardpisces** [comment]
+1 
can anybody give us an answer?

**Comment by AnibalMercadolibre** [comment]
+1
