### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 	 in JSON at position 145

### ISSUE THREAD

**Issue by DFOXpro** [jakesankey/git-history#43]
[Enter steps to reproduce:]

1. Install Git-history in Atom 1.15
2. Launch the history view then it crash
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package 3.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected token 	 in JSON at position 145

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token 	 in JSON at position 145
    at Object.parse (native)
    at stdout (/packages/git-history/lib/git-history-view.coffee:47:13)
    at /app.asar/src/buffered-process.js:196:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -1:14.9.0 editor:consolidate-selections (input.hidden-input)
     -1:14.9.0 core:cancel (input.hidden-input)
     -1:14.1.0 command-palette:toggle (input.hidden-input)
     -1:10.8.0 core:confirm (input.hidden-input)
     -1:10.7.0 git-control:toggle (input.hidden-input)
     -0:22.8.0 intentions:highlight (input.hidden-input)
     -0:22.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:21.2.0 editor:consolidate-selections (input.hidden-input)
     -0:21.2.0 core:cancel (input.hidden-input)
     -0:20.7.0 intentions:highlight (input.hidden-input)
     -0:20.5.0 command-palette:toggle (input.hidden-input)
     -0:14.6.0 core:move-down (input.hidden-input)
     -0:13.2.0 core:confirm (input.hidden-input)
     -0:13.2.0 git-history:show-file-history (input.hidden-input)
     -0:10.8.0 editor:consolidate-selections (input.hidden-input)
     -0:10.8.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
aligner 0.22.3 
aligner-ruby 1.5.0 
atom-beautify 0.29.17 
atom-jade 0.3.0 
build-rake 0.1.1 
busy-signal 1.3.0 
coffee-autocompile 0.6.2 
file-icons 2.1.1 
force-tab 0.2.2 
git-history 3.3.0 
git-log 0.4.1 
git-plus 5.16.2 
git-time-machine 1.5.9 
grunt-runner 0.14.0 
increment-selection 0.3.0 
intentions 1.1.2 
language-coffee-script-angular 2.2.0 
language-haml 0.24.1 
language-jade 0.7.2 
language-markdown 0.20.0 
language-pug 0.0.21 
linter 2.1.2 
linter-coffees6 2.0.0 
linter-pug 1.3.1 
linter-ruby 1.2.5 
linter-ui-default 1.2.2 
run-command2 1.12.2 
sort-lines 0.14.0 
Stylus 3.1.0 
tree-view-git-branch 0.1.2 
```

**Comment by dhniels** [comment]
getting this error as well. seems to be only happening on one of my files that i can tell so far.
