### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 	 in JSON at position 277

### ISSUE THREAD

**Issue by ByJacob** [jakesankey/git-history#53]
[Enter steps to reproduce:]

1. Open  git history for one file

git log -p file

    commit 401ff9830128ae79f5916ac27879cdd95388d475
    Author: PERSON <m.scheffler@kentaur-solutions.cc>
    Date:   Tue Jan 24 11:32:59 2017 +0100
    TAG #comment comment
    TAG #comm#   comment
    diff --git a/path b/path
    new file mode 100644
    index 000000000..feb82974c
    --- /dev/null
    +++ b/path
    @@ -0,0 +1,90 @@
    +version: '2'
    +
    + docker-compose file

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package 3.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected token 	 in JSON at position 277

```
At file:///C:/Users/j.rosa/AppData/Local/atom/app-1.38.2/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token 	 in JSON at position 277
    at JSON.parse (<anonymous>)
    at stdout (/packages/git-history/lib/git-history-view.coffee:47:13)
    at Socket.e.on.e (~/AppData/Local/atom/app-1.38.2/resources/app/static/<embedded>:14:1118051)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -3:12.6.0 core:move-down (input.hidden-input)
     -3:12.2.0 core:move-up (input.hidden-input)
     -3:09.7.0 core:confirm (input.hidden-input)
     -3:09.7.0 open-on-github:history (input.hidden-input)
     -2:56.4.0 command-palette:toggle (input.hidden-input)
     -2:53.1.0 core:move-down (input.hidden-input)
     -2:52.8.0 core:move-up (input.hidden-input)
     -2:52.5.0 core:confirm (input.hidden-input)
     -2:52.5.0 git-history:show-file-history (input.hidden-input)
     -2:18 command-palette:toggle (input.hidden-input)
     -2:15.3.0 core:move-down (input.hidden-input)
     -2:15 core:move-up (input.hidden-input)
     -2:13.3.0 core:confirm (input.hidden-input)
     -2:13.3.0 git-history:show-file-history (input.hidden-input)
     -1:19.7.0 tree-view:show-current-file-in-file-manager (div.title)
     -0:11.3.0 tree-view:remove (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
git-diff-details 1.4.0 
git-history 3.3.0 
minimap-git-diff 4.3.1 
```

**Comment by ByJacob** [comment]
Close issue because this repo is death
