### ISSUE TITLE
Uncaught TypeError: Callback must be a function

### ISSUE THREAD

**Issue by jdknopp** [jakesankey/git-history#56]
[Enter steps to reproduce:]

1. Open git controlled file
2. Select Packages -> Git History -> Show file history
3. Click a log entry

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 18.04.4
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package 3.3.0

### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:146

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:146:11)
    at Object.mkdir (fs.js:747:14)
    at /packages/git-history/lib/git-history-view.coffee:104:20
    at n (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:14:1063432)
    at /snap/atom/252/usr/share/atom/resources/app/static/<embedded>:14:1063520
    at Socket.<anonymous> (/snap/atom/252/usr/share/atom/resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
     -0:59.2.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16 git-history:show-file-history (input.hidden-input)
```

### Non-Core Packages

```
git-history 3.3.0 
```

**Comment by Endzel** [comment]
Same happening from:
**Atom**: 1.48.0 x64
**OS**: macOS Catalina 10.15.5
**Thrown From**: git-history package 3.3.0

**Comment by KerekesDavid** [comment]
Same here:

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 19.10
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package 3.3.0


### Stack Trace

Uncaught TypeError: Callback must be a function

```
At fs.js:146

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:146:11)
    at Object.mkdir (fs.js:747:14)
    at /packages/git-history/lib/git-history-view.coffee:104:20
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1063432)
    at /usr/share/atom/resources/app/static/<embedded>:14:1063520
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)
```

### Commands

```
     -1:01.5.0 intentions:highlight (input.hidden-input)
     -1:01.4.0 git-plus:menu (input.hidden-input)
     -1:00.0 editor:consolidate-selections (input.hidden-input)
     -1:00.0 core:cancel (input.hidden-input)
     -0:59.6.0 intentions:highlight (input.hidden-input)
     -0:59.3.0 git-history:show-file-history (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-terminal 0.8.0 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
git-blame 1.8.0 
git-history 3.3.0 
git-plus 8.7.1 
highlight-selected 0.17.0 
intentions 1.1.5 
language-latex 1.2.0 
language-markdown 0.37.0 
language-prolog 0.11.0 
latex 0.50.2 
latex-completions 0.3.6 
linter 2.3.1 
linter-markdown 5.2.11 
linter-prolog 0.2.1 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
markdown-writer 2.11.10 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
pdf-view 0.72.0 
python-tools 0.6.9 
```

**Comment by Guymer** [comment]
Same here with Atom 1.51.0 on MacOS
