### ISSUE TITLE
Uncaught TypeError: Callback must be a function. Received undefined

### ISSUE THREAD

**Issue by fydem-com** [jakesankey/git-history#57]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.14.4
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package 3.3.0

### Stack Trace

Uncaught TypeError: Callback must be a function. Received undefined

```
At fs.js:150

TypeError [ERR_INVALID_CALLBACK] [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:150:11)
    at Object.mkdir (fs.js:735:14)
    at /packages/git-history/lib/git-history-view.coffee:104:20
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1088976)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1089064
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1087732)
    at Socket.emit (events.js:205:15)
    at Pipe.<anonymous> (net.js:586:12)
```

### Commands

```
     -0:54.7.0 command-palette:toggle (input.hidden-input)
     -0:48.6.0 git-history:show-file-history (input.hidden-input)
     -0:32 editor:consolidate-selections (input.hidden-input)
     -0:32 core:cancel (input.hidden-input)
     -0:14.2.0 command-palette:toggle (input.hidden-input)
     -0:09.2.0 git-history:show-file-history (input.hidden-input)
     -0:04.4.0 editor:consolidate-selections (input.hidden-input)
     -0:04.4.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
git-history 3.3.0 
```

**Comment by facundobianco** [comment]
There is any update?

**Comment by sjaredj** [comment]
Would love to use this package but getting the same error as above
