### ISSUE TITLE
Uncaught SyntaxError: Unexpected token m

### ISSUE THREAD

**Issue by obelich** [jakesankey/git-history#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.174.0
**System**: linux 3.16.0-29-generic
**Thrown From**: [git-history](https://github.com/jakesankey/git-history) package, v1.1.3
### Stack Trace

Uncaught SyntaxError: Unexpected token m

```
At file:///usr/share/atom/resources/app/static/index.html?loadSettings=%7B%22pathToOpen%22%3A%22%2Fvar%2Fwww%2Fhtml%2Fdolphin%22%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.174.0%22%2C%22initialPath%22%3A%22%2Fvar%2Fwww%2Fhtml%2Fdolphin%22%7D:2

SyntaxError: Unexpected token m
  at Object.parse (native)
  at stdout (/home/obelich/.atom/packages/git-history/lib/git-history-view.coffee:26:13)
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:137:13)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at Socket.Readable.push (_stream_readable.js:125:10)
  at Pipe.onread (net.js:522:20)

```
### Commands

```
  2x -2:28.2 core:backspace (atom-text-editor.editor)
     -2:25.5 core:save (atom-text-editor.editor)
  2x -2:24.2 core:undo (atom-text-editor.editor)
     -0:01.8 application:open-file (atom-text-editor.editor)
     -0:00.0 git-history:show-file-history (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-html-preview",
      "autocomplete-plus"
    ],
    "themes": [
      "seti-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  },
  "git-history": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v0.9.1
autocomplete-snippets, v0.3.2
cakephp-snippets, v0.6.0
color-picker, v1.3.0
git-history, v1.1.3
monokai, v0.10.0
robin-language-php, v0.9.0
seti-ui, v0.6.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by jakesankey** [comment]
Please update to the latest version of the plugin (and Atom of course). This issue should be resolved.
